In [29]:
import pandas as pd
from datetime import *

In [37]:
df = pd.read_csv('cases-by-day.csv')

In [83]:
df.head()

,date_of_interest,CASE_COUNT,PROBABLE_CASE_COUNT,CASE_COUNT_7DAY_AVG,ALL_CASE_COUNT_7DAY_AVG,BX_CASE_COUNT,BX_PROBABLE_CASE_COUNT,BX_CASE_COUNT_7DAY_AVG,BX_ALL_CASE_COUNT_7DAY_AVG,BK_CASE_COUNT,...,QN_CASE_COUNT_7DAY_AVG,QN_ALL_CASE_COUNT_7DAY_AVG,SI_CASE_COUNT,SI_PROBABLE_CASE_COUNT,SI_CASE_COUNT_7DAY_AVG,SI_ALL_CASE_COUNT_7DAY_AVG,INCOMPLETE,month,day,year
0,02/29/2020,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,02,29,2020
1,03/01/2020,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,03,01,2020
2,03/02/2020,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,03,02,2020
3,03/03/2020,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,03,03,2020
4,03/04/2020,5,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,03,04,2020

In [65]:
mn_pop = 1694263
nyc_pop = 8804190
p_mn_nyc = mn_pop/nyc_pop
p_mn_nyc

0.1924382595105285

In [44]:
df[['month', 'day', 'year']] = df['date_of_interest'].str.split('/', expand=True)

In [45]:
df

,date_of_interest,CASE_COUNT,PROBABLE_CASE_COUNT,CASE_COUNT_7DAY_AVG,ALL_CASE_COUNT_7DAY_AVG,BX_CASE_COUNT,BX_PROBABLE_CASE_COUNT,BX_CASE_COUNT_7DAY_AVG,BX_ALL_CASE_COUNT_7DAY_AVG,BK_CASE_COUNT,...,QN_CASE_COUNT_7DAY_AVG,QN_ALL_CASE_COUNT_7DAY_AVG,SI_CASE_COUNT,SI_PROBABLE_CASE_COUNT,SI_CASE_COUNT_7DAY_AVG,SI_ALL_CASE_COUNT_7DAY_AVG,INCOMPLETE,month,day,year
0,02/29/2020,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,02,29,2020
1,03/01/2020,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,03,01,2020
2,03/02/2020,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,03,02,2020
3,03/03/2020,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,03,03,2020
4,03/04/2020,5,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,03,04,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,09/01/2022,1606,448,1601,2027,255,87,254,351,446,...,477,606,94,23,104,130,60890,09,01,2022
916,09/02/2022,1430,382,1567,1991,232,81,251,346,442,...,463,594,86,19,101,127,60890,09,02,2022
917,09/03/2022,883,316,1537,1963,143,55,245,339,204,...,454,584,83,14,102,128,60890,09,03,2022
918,09/04/2022,930,334,1512,1937,121,54,239,329,264,...,447,579,86,23,105,132,60890,09,04,2022
919,09/05/2022,918,319,1338,1728,139,57,208,287,274,...,400,525,65,30,92,116,60890,09,05,2022

In [51]:
df2 = df[(df['month'] == '01') & (df['year'] == '2021')]

In [53]:
mn_cases_jan = df2['MN_CASE_COUNT'].sum()

In [57]:
nyc_cases_jan = df2['CASE_COUNT'].sum()

In [75]:
prob_pos_mn = mn_cases_jan/mn_pop
prob_pos_mn

0.011412041696005874

In [76]:
prob_pos_nyc = nyc_cases_jan/nyc_pop
prob_pos_nyc

0.015741822927492478

In [77]:
prob_parta = prob_pos_mn/p_mn_nyc

In [78]:
prob_parta

0.059302353518643776

part b

In [79]:
prob_partb = prob_pos_mn/prob_pos_nyc

In [80]:
prob_partb

0.7249504551391688

In [33]:
df['date_of_interest'] = df['date_of_interest'].map(lambda x: dt.datetime.strptime(x,'%m/%d/%Y'))

In [36]:
d = date(1,1,2021)
e = date(1,31,2021)

ValueError: day is out of range for month

In [35]:
df2 = df[(df['date_of_interest'] >=  1/ 1/2021) & (df['date_of_interest'] <= 1/31/2021)]

TypeError: Invalid comparison between dtype=datetime64[ns] and float